#!/usr/bin/perl

use Test::Simple tests => 10;
use File::Slurp;

# test01		default maxcol,maxrow = 1,1
# test02		'+','-','=' and ' '
# test03		regular expressions,'+N' and '-N'
# test04		ranges and using mixed `ranges/*' and `ranges/relatives' addresses
# test05		header cells and header-status-overwrite
# test06		cell arrtibutes and table caption
# test07		location tags and postprocessor
# test08		multi-line entries, table nesting, location tags and preprocessor in nested tables
# test09		arbitrary perl code addresses and mixed 'code/relative' and 'code/*' addresses
# test10		colspan and rowspan

for(1..10) {
  my $in_path  = sprintf "testsuite/test%02d.in", $_;
  my $out_path = sprintf "testsuite/test%02d.out", $_;
  my $actual   = `./freetable <$in_path`;
  my $expected = read_file($out_path);
  ok($actual eq $expected);
}
